batch_size: 128
clip_grad: 3.0
config: config.yaml
data_location: /data/imagenet100/train
data_set: ImageFolder
dist_url: env://
drop_align: 1
drop_only: 1
drop_perc: 0.75
drop_replace: 0.3
drop_type: noise
epochs: 800
global_crops_scale: !!python/tuple
- 0.25
- 1.0
img_size: 224
local_crops_number: 0
local_crops_scale: !!python/tuple
- 0.05
- 0.4
local_rank: 0
lr: 0.0005
min_lr: 1.0e-06
model: vit_tiny
num_workers: 10
output_dir: outputs/SiTv3
recons_blocks: 6-8-10-12
saveckp_freq: 20
seed: 0
use_fp16: true
warmup_epochs: 10
weight_decay: 0.04
weight_decay_end: 0.4
